
export const countriesList = [
  { value: "not-specified", label: "Not specified" },
  { value: "USA", label: "UNITED STATES" },
  { value: "ALB", label: "ALBANIA" },
  { value: "DZA", label: "ALGERIA" },
  { value: "ASM", label: "AMERICAN SAMOA" },
  { value: "AND", label: "ANDORRA" },
  { value: "AGO", label: "ANGOLA" },
  { value: "AIA", label: "ANGUILLA" },
  { value: "ATA", label: "ANTARCTICA" },
  { value: "ATG", label: "ANTIGUA AND BARBUDA" },
  { value: "ARG", label: "ARGENTINA" },
  { value: "ARM", label: "ARMENIA" },
  { value: "ABW", label: "ARUBA" },
  { value: "AUS", label: "AUSTRALIA" },
  { value: "AUT", label: "AUSTRIA" },
  { value: "AZE", label: "AZERBAIJAN" },
  { value: "BHS", label: "BAHAMAS" },
  { value: "BHR", label: "BAHRAIN" },
  { value: "BGD", label: "BANGLADESH" },
  { value: "BRB", label: "BARBADOS" },
  { value: "BLR", label: "BELARUS" },
  { value: "BEL", label: "BELGIUM" },
  { value: "BLZ", label: "BELIZE" },
  { value: "BEN", label: "BENIN" },
  { value: "BMU", label: "BERMUDA" },
  { value: "BTN", label: "BHUTAN" },
  { value: "BOL", label: "BOLIVIA" },
  { value: "BIH", label: "BOSNIA AND HERZEGOVINA" },
  { value: "BWA", label: "BOTSWANA" },
  { value: "BVT", label: "BOUVET ISLAND" },
  { value: "BRA", label: "BRAZIL" },
  { value: "IOT", label: "BRITISH INDIAN OCEAN TERRITORY" },
  { value: "BRN", label: "BRUNEI DARUSSALAM" },
  { value: "BGR", label: "BULGARIA" },
  { value: "BFA", label: "BURKINA FASO" },
  { value: "BDI", label: "BURUNDI" },
  { value: "KHM", label: "CAMBODIA" },
  { value: "CMR", label: "CAMEROON" },
  { value: "CAN", label: "CANADA" },
  { value: "CPV", label: "CAPE VERDE" },
  { value: "CYM", label: "CAYMAN ISLANDS" },
  { value: "CAF", label: "CENTRAL AFRICAN REPUBLIC" },
  { value: "TCD", label: "CHAD" },
  { value: "CHL", label: "CHILE" },
  { value: "CHN", label: "CHINA" },
  { value: "CXR", label: "CHRISTMAS ISLAND" },
  { value: "CCK", label: "COCOS (KEELING) ISLANDS" },
  { value: "COL", label: "COLOMBIA" },
  { value: "COM", label: "COMOROS" },
  { value: "COG", label: "CONGO" },
  { value: "COK", label: "COOK ISLANDS" },
  { value: "CRI", label: "COSTA RICA" },
  { value: "CIV", label: "COTE D'IVOIRE" },
  { value: "HRV", label: "CROATIA" },
  { value: "CYP", label: "CYPRUS" },
  { value: "CZE", label: "CZECH REPUBLIC" },
  { value: "DNK", label: "DENMARK" },
  { value: "DJI", label: "DJIBOUTI" },
  { value: "DMA", label: "DOMINICA" },
  { value: "DOM", label: "DOMINICAN REPUBLIC" },
  { value: "TMP", label: "EAST TIMOR" },
  { value: "ECU", label: "ECUADOR" },
  { value: "EGY", label: "EGYPT" },
  { value: "SLV", label: "EL SALVADOR" },
  { value: "GNQ", label: "EQUATORIAL GUINEA" },
  { value: "ERI", label: "ERITREA" },
  { value: "EST", label: "ESTONIA" },
  { value: "ETH", label: "ETHIOPIA" },
  { value: "FLK", label: "FALKLAND ISLANDS (MALVINAS)" },
  { value: "FRO", label: "FAROE ISLANDS" },
  { value: "FJI", label: "FIJI" },
  { value: "FIN", label: "FINLAND" },
  { value: "FRA", label: "FRANCE" },
  { value: "FXX", label: "FRANCE, METROPOLITAN" },
  { value: "GUF", label: "FRENCH GUIANA" },
  { value: "PYF", label: "FRENCH POLYNESIA" },
  { value: "ATF", label: "FRENCH SOUTHERN TERRITORIES" },
  { value: "GAB", label: "GABON" },
  { value: "GMB", label: "GAMBIA" },
  { value: "GEO", label: "GEORGIA" },
  { value: "DEU", label: "GERMANY" },
  { value: "GHA", label: "GHANA" },
  { value: "GIB", label: "GIBRALTAR" },
  { value: "GRC", label: "GREECE" },
  { value: "GRL", label: "GREENLAND" },
  { value: "GRD", label: "GRENADA" },
  { value: "GLP", label: "GUADELOUPE" },
  { value: "GUM", label: "GUAM" },
  { value: "GTM", label: "GUATEMALA" },
  { value: "GIN", label: "GUINEA" },
  { value: "GNB", label: "GUINEA-BISSAU" },
  { value: "GUY", label: "GUYANA" },
  { value: "HTI", label: "HAITI" },
  { value: "HMD", label: "HEARD AND MC DONALD ISLANDS" },
  { value: "HND", label: "HONDURAS" },
  { value: "HKG", label: "HONG KONG" },
  { value: "HUN", label: "HUNGARY" },
  { value: "ISL", label: "ICELAND" },
  { value: "IND", label: "INDIA" },
  { value: "IDN", label: "INDONESIA" },
  { value: "IRQ", label: "IRAQ" },
  { value: "IRL", label: "IRELAND" },
  { value: "ISR", label: "ISRAEL" },
  { value: "ITA", label: "ITALY" },
  { value: "JAM", label: "JAMAICA" },
  { value: "JPN", label: "JAPAN" },
  { value: "JOR", label: "JORDAN" },
  { value: "KAZ", label: "KAZAKHSTAN" },
  { value: "KEN", label: "KENYA" },
  { value: "KIR", label: "KIRIBATI" },
  { value: "KOR", label: "KOREA, REPUBLIC OF" },
  { value: "KWT", label: "KUWAIT" },
  { value: "KGZ", label: "KYRGYZSTAN" },
  { value: "LAO", label: "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
  { value: "LVA", label: "LATVIA" },
  { value: "LBN", label: "LEBANON" },
  { value: "LSO", label: "LESOTHO" },
  { value: "LBR", label: "LIBERIA" },
  { value: "LBY", label: "LIBYA" },
  { value: "LIE", label: "LIECHTENSTEIN" },
  { value: "LTU", label: "LITHUANIA" },
  { value: "LUX", label: "LUXEMBOURG" },
  { value: "MAC", label: "MACAU" },
  { value: "MKD", label: "MACEDONIA, THE FORMER YUGOSLAV" },
  { value: "MDG", label: "MADAGASCAR" },
  { value: "MWI", label: "MALAWI" },
  { value: "MYS", label: "MALAYSIA" },
  { value: "MDV", label: "MALDIVES" },
  { value: "MLI", label: "MALI" },
  { value: "MLT", label: "MALTA" },
  { value: "MHL", label: "MARSHALL ISLANDS" },
  { value: "MTQ", label: "MARTINIQUE" },
  { value: "MRT", label: "MAURITANIA" },
  { value: "MUS", label: "MAURITIUS" },
  { value: "MYT", label: "MAYOTTE" },
  { value: "MEX", label: "MEXICO" },
  { value: "FSM", label: "MICRONESIA, FEDERATED STATES OF" },
  { value: "MDA", label: "MOLDOVA, REPUBLIC OF" },
  { value: "MCO", label: "MONACO" },
  { value: "MNG", label: "MONGOLIA" },
  { value: "MSR", label: "MONTSERRAT" },
  { value: "MAR", label: "MOROCCO" },
  { value: "MOZ", label: "MOZAMBIQUE" },
  { value: "MMR", label: "MYANMAR" },
  { value: "NAM", label: "NAMIBIA" },
  { value: "NRU", label: "NAURU" },
  { value: "NPL", label: "NEPAL" },
  { value: "NLD", label: "NETHERLANDS" },
  { value: "ANT", label: "NETHERLANDS ANTILLES" },
  { value: "NCL", label: "NEW CALEDONIA" },
  { value: "NZL", label: "NEW ZEALAND" },
  { value: "NIC", label: "NICARAGUA" },
  { value: "NER", label: "NIGER" },
  { value: "NGA", label: "NIGERIA" },
  { value: "NIU", label: "NIUE" },
  { value: "NFK", label: "NORFOLK ISLAND" },
  { value: "MNP", label: "NORTHERN MARIANA ISLANDS" },
  { value: "NOR", label: "NORWAY" },
  { value: "OMN", label: "OMAN" },
  { value: "PAK", label: "PAKISTAN" },
  { value: "PLW", label: "PALAU" },
  { value: "PAN", label: "PANAMA" },
  { value: "PNG", label: "PAPUA NEW GUINEA" },
  { value: "PRY", label: "PARAGUAY" },
  { value: "PER", label: "PERU" },
  { value: "PHL", label: "PHILIPPINES" },
  { value: "PCN", label: "PITCAIRN" },
  { value: "POL", label: "POLAND" },
  { value: "PRT", label: "PORTUGAL" },
  { value: "PRI", label: "PUERTO RICO" },
  { value: "QAT", label: "QATAR" },
  { value: "REU", label: "REUNION" },
  { value: "ROM", label: "ROMANIA" },
  { value: "RUS", label: "RUSSIAN FEDERATION" },
  { value: "RWA", label: "RWANDA" },
  { value: "KNA", label: "SAINT KITTS AND NEVIS" },
  { value: "LCA", label: "SAINT LUCIA" },
  { value: "VCT", label: "SAINT VINCENT AND THE GRENADINES" },
  { value: "WSM", label: "SAMOA" },
  { value: "SMR", label: "SAN MARINO" },
  { value: "STP", label: "SAO TOME AND PRINCIPE" },
  { value: "SAU", label: "SAUDI ARABIA" },
  { value: "SEN", label: "SENEGAL" },
  { value: "SRB", label: "SERBIA" },
  { value: "SYC", label: "SEYCHELLES" },
  { value: "SLE", label: "SIERRA LEONE" },
  { value: "SGP", label: "SINGAPORE" },
  { value: "SVK", label: "SLOVAKIA" },
  { value: "SVN", label: "SLOVENIA" },
  { value: "SLB", label: "SOLOMON ISLANDS" },
  { value: "SOM", label: "SOMALIA" },
  { value: "ZAF", label: "SOUTH AFRICA" },
  { value: "SGS", label: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" },
  { value: "ESP", label: "SPAIN" },
  { value: "LKA", label: "SRI LANKA" },
  { value: "SHN", label: "ST. HELENA" },
  { value: "SPM", label: "ST. PIERRE AND MIQUELON" },
  { value: "SDN", label: "SUDAN" },
  { value: "SUR", label: "SURINAME" },
  { value: "SJM", label: "SVALBARD AND JAN MAYEN ISLANDS" },
  { value: "SWZ", label: "SWAZILAND" },
  { value: "SWE", label: "SWEDEN" },
  { value: "CHE", label: "SWITZERLAND" },
  { value: "TWN", label: "TAIWAN" },
  { value: "TJK", label: "TAJIKISTAN" },
  { value: "TZA", label: "TANZANIA, UNITED REPUBLIC OF" },
  { value: "THA", label: "THAILAND" },
  { value: "TGO", label: "TOGO" },
  { value: "TKL", label: "TOKELAU" },
  { value: "TON", label: "TONGA" },
  { value: "TTO", label: "TRINIDAD AND TOBAGO" },
  { value: "TUN", label: "TUNISIA" },
  { value: "TUR", label: "TURKEY" },
  { value: "TKM", label: "TURKMENISTAN" },
  { value: "TCA", label: "TURKS AND CAICOS ISLANDS" },
  { value: "TUV", label: "TUVALU" },
  { value: "UGA", label: "UGANDA" },
  { value: "UKR", label: "UKRAINE" },
  { value: "ARE", label: "UNITED ARAB EMIRATES" },
  { value: "GBR", label: "UNITED KINGDOM" },
  { value: "UMI", label: "UNITED STATES MINOR OUTLYING ISLANDS" },
  { value: "URY", label: "URUGUAY" },
  { value: "UZB", label: "UZBEKISTAN" },
  { value: "VUT", label: "VANUATU" },
  { value: "VAT", label: "VATICAN CITY STATE (HOLY SEE)" },
  { value: "VEN", label: "VENEZUELA" },
  { value: "VNM", label: "VIET NAM" },
  { value: "VGB", label: "VIRGIN ISLANDS (BRITISH)" },
  { value: "VIR", label: "VIRGIN ISLANDS (U.S.)" },
  { value: "WLF", label: "WALLIS AND FUTUNA ISLANDS" },
  { value: "ESH", label: "WESTERN SAHARA" },
  { value: "YEM", label: "YEMEN" },
  { value: "YUG", label: "YUGOSLAVIA" },
  { value: "ZAR", label: "ZAIRE" },
  { value: "ZMB", label: "ZAMBIA" },
  { value: "ZWE", label: "ZIMBABWE" },
];
