export const productCategories = [
  {
    id: 12,
    name: "Headphones",
    slug: "headphones",
    description: null,
    is_visible: 0,
    parent_id: null,
    subcategories: [
      {
        id: 17,
        name: "Handsfree",
        slug: "handsfree",
        description: null,
        is_visible: 1,
        parent_id: 12,
        subcategories: [
          {
            id: 25,
            name: "netcable",
            slug: "netcable",
            description: null,
            is_visible: 0,
            parent_id: 17,
            subcategories: [],
          },
          {
            id: 31,
            name: "Hubs",
            slug: "hubs",
            description: null,
            is_visible: 1,
            parent_id: 17,
            subcategories: [],
          },
        ],
      },
      {
        id: 26,
        name: "logitech",
        slug: "logitech",
        description: null,
        is_visible: 0,
        parent_id: 12,
        subcategories: [],
      },
    ],
  },
  {
    id: 13,
    name: "Electronics",
    slug: "electronics",
    description: null,
    is_visible: 0,
    parent_id: null,
    subcategories: [
      {
        id: 18,
        name: "DataCable",
        slug: "datacable",
        description: null,
        is_visible: 1,
        parent_id: 13,
        subcategories: [
          {
            id: 26,
            name: "Ethernet",
            slug: "ethernet",
            description: null,
            is_visible: 0,
            parent_id: 18,
            subcategories: [],
          },
          {
            id: 27,
            name: "ports",
            slug: "ports",
            description: null,
            is_visible: 1,
            parent_id: 18,
            subcategories: [],
          },
        ],
      },
      {
        id: 42,
        name: "Mouse",
        slug: "mouse",
        description: null,
        is_visible: 0,
        parent_id: 13,
        subcategories: [],
      },
    ],
  },
];