import { Home, ShoppingCart, Users, Store, LineChart, Gift, Settings, AppWindow, Layers, Banknote, Megaphone } from "lucide-react";

export const sidebarData = [
  {
    title: "Home",
    url: "/manage/dashboard",
    icon: Home,
  },
  {
    title: "Orders",
    icon: ShoppingCart,
    children: [
      { title: "All Orders", url: "/manage/orders" },
      { title: "Add", url: "/manage/orders/add" },
      { title: "Search", url: "/manage/orders/search" },
      { title: "Export", url: "/manage/orders/export" },
      { title: "Draft Orders", url: "/manage/orders/draft" },
      { title: "Shipments", url: "/manage/orders/shipments" },
      { title: "Return request", url: "/manage/orders/returns" },
      { title: "Tracking Numbers", url: "/manage/orders/tracking" },
      { title: "Gift Certificates", url: "/manage/orders/gifts" },
    ],
  },
  {
    title: "Products",
    icon: Gift,
    children: [
      { title: "All Products", url: "/manage/products" },
      { title: "Add", url: "/manage/products/add" },
      { title: "Search", url: "/manage/products/search" },
      { title: "Import", url: "/manage/products/import" },
      { title: "Export", url: "/manage/products/export" },
      { title: "Categories", url: "/manage/products/categories" },
      { title: "Options", url: "/manage/products/options" },
      { title: "Filtering", url: "/manage/products/filtering" },
      { title: "Reviews", url: "/manage/products/reviews" },
      { title: "Price Lists", url: "/manage/products/price-lists" },
      { title: "Brands", url: "/manage/products/brands" },
      { title: "Import SKUs", url: "/manage/products/import-skus" },
      { title: "Export SKUs", url: "/manage/products/export-skus" },
    ],
  },
  {
    title: "Customers",
    icon: Users,
    children: [
      { title: "All Customers", url: "/manage/customers" },
      { title: "Add", url: "/manage/customers/add" },
      { title: "Search", url: "/manage/customers/search" },
      { title: "Import", url: "/manage/customers/import" },
      { title: "Export", url: "/manage/customers/export" },
      { title: "Customer Groups", url: "/manage/customers/groups" },
    ],
  },
  {
    title: "Storefront",
    icon: Store,
    children: [
      { title: "Themes", url: "/storefront/themes" },
      { title: "Themes MarketPlace", url: "/storefront/themes-marketplace" },
      { title: "Logo", url: "/storefront/logo" },
      { title: "Home Page Carousel", url: "/storefront/carousel" },
      { title: "Social Media Links", url: "/storefront/social-media" },
      { title: "Script Manager", url: "/storefront/scripts" },
      { title: "Web Pages", url: "/storefront/web-pages" },
      { title: "Blog", url: "/storefront/blog" },
      { title: "Image Manager", url: "/storefront/images" },
    ],
  },
  { title: "Marketing", icon: Megaphone, url: "/marketing" },
  { title: "Analytics", icon: LineChart, url: "/analytics" },
  { title: "Apps", icon: AppWindow, url: "/apps" },
  { title: "Channels", icon: Layers, url: "/channels" },
  { title: "Financing", icon: Banknote, url: "/financing" },
  { title: "Settings", icon: Settings, url: "/settings" },
];
