//src/app/layout.sx
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/Providers";
import { Cabin } from "next/font/google";
import ProtectedLayout from "@/auth/ProtectedLayout";

const cabin = Cabin ({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${cabin.className} antialiased`}
      >
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  );
}
